# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chat(object):
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(527, 118)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Chat.sizePolicy().hasHeightForWidth())
        Chat.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Chat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Chat)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name = QtWidgets.QLabel(self.frame)
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name)
        self.LastMessage = QtWidgets.QLabel(self.frame)
        self.LastMessage.setAutoFillBackground(False)
        self.LastMessage.setObjectName("LastMessage")
        self.verticalLayout_2.addWidget(self.LastMessage)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, Chat):
        _translate = QtCore.QCoreApplication.translate
        Chat.setWindowTitle(_translate("Chat", "Form"))
        self.Name.setText(_translate("Chat", "Name"))
        self.LastMessage.setText(_translate("Chat", "Last message"))
