# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_message(object):
    def setupUi(self, message):
        message.setObjectName("message")
        message.resize(200, 58)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(message.sizePolicy().hasHeightForWidth())
        message.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(message)
        self.gridLayout.setObjectName("gridLayout")
        self.time = QtWidgets.QLabel(message)
        self.time.setMaximumSize(QtCore.QSize(16777215, 15))
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 1, 0, 1, 1)
        self.messageLabel = QtWidgets.QTextBrowser(message)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageLabel.sizePolicy().hasHeightForWidth())
        self.messageLabel.setSizePolicy(sizePolicy)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 0, 0, 1, 1)

        self.retranslateUi(message)
        QtCore.QMetaObject.connectSlotsByName(message)

    def retranslateUi(self, message):
        _translate = QtCore.QCoreApplication.translate
        message.setWindowTitle(_translate("message", "Form"))
        self.time.setText(_translate("message", "TextLabel"))
